CREATE PROCEDURE dbo.FI_SP_IncBeneficiarioV2
    @IDCLIENTE BIGINT,
    @CPF VARCHAR(11),
    @NOME VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.BENEFICIARIOS (IDCLIENTE, CPF, NOME)
    VALUES (@IDCLIENTE, @CPF, @NOME);

    SELECT SCOPE_IDENTITY()
END
